version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pip'
    directory: '/systems/http-api'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pip'
    directory: '/systems/infrastructure'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
