encryptionsalt: v1:nHmOvsM5LZs=:v1:+Bq4T0xxVmP89fxW:+tqFjfMChyazp0b8EVbkfgIi9gY//A==
config:
  gcp:project: spotify-music-player-327914
  gcp:region: europe-west2
  gcp:zone: europe-west2-a
  name:prefix: spotify-music-player
  domain:prefix: spotify-music-player-demo
