@startuml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.3.0

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include ICONURL/common.puml
!include ICONURL/devicons/react.puml
!include ICONURL/devicons/redis.puml

Person(user, "Customer", "People that need products")
Container(spa, "SPA", "react", "The main interface that the customer interacts with", $sprite="react")
Container(api, "API", "???", "Get recommendation feed")
ContainerDb(db, "Cache", "Redis", "Holds user recommended feed", $sprite="redis")
Container(spotify, "Spotify API", "External API", "Get recommendation feed")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Get recommendation feed", "https")
Rel_R(api, db, "Reads/Writes")
Rel(api, spotify, "Reads if cache not set")

@enduml