import { renderHook } from '@testing-library/react-hooks';

import { createPollyContext } from '../../../../../testHelper/createPollyContext';
import { TestApp } from '../../../../App';
import { useTopStreamingAlbum } from '../useTopStreamingAlbum';

const context = createPollyContext();
describe('Test useTopStreamingAlbum', () => {
  it('fetch track report and the get track details to show albumn', async () => {
    context.polly.server.host('http://localhost', () => {
      context.polly.server
        .get('/.netlify/functions/fetch-top-stream-report')
        .intercept((_, res) => {
          res.status(200).json({
            data: {
              items: [
                {
                  artist: 'Terence Lam',
                  position: '1',
                  streams: '168161',
                  trackId: '32QnXosZq7A11knnBAEqk7',
                  trackName: '一人之境 in C major',
                  url: 'https://open.spotify.com/track/32QnXosZq7A11knnBAEqk7',
                },
                {
                  artist: 'Terence Lam',
                  position: '2',
                  streams: '141195',
                  trackId: '63QmxPL3QlchvXcHLsI6UM',
                  trackName: '時光倒流一句話',
                  url: 'https://open.spotify.com/track/63QmxPL3QlchvXcHLsI6UM',
                },
                {
                  artist: 'Jace Chan',
                  position: '3',
                  streams: '135240',
                  trackId: '4xL01OuFjqizPDclF8gDpl',
                  trackName: '隔離 - Studio Live Duet',
                  url: 'https://open.spotify.com/track/4xL01OuFjqizPDclF8gDpl',
                },
                {
                  artist: 'Olivia Rodrigo',
                  position: '4',
                  streams: '132371',
                  trackId: '7lPN2DXiMsVn7XUKtOW1CS',
                  trackName: 'drivers license',
                  url: 'https://open.spotify.com/track/7lPN2DXiMsVn7XUKtOW1CS',
                },
                {
                  artist: 'Terence Lam',
                  position: '5',
                  streams: '123274',
                  trackId: '0Q3jOuEpx8Esi2qZMQSghl',
                  trackName: '下一位前度',
                  url: 'https://open.spotify.com/track/0Q3jOuEpx8Esi2qZMQSghl',
                },
                {
                  artist: 'Crowd Lu',
                  position: '6',
                  streams: '114595',
                  trackId: '3OC84eKMxRJ4x0Hcwl9i4i',
                  trackName:
                    '刻在我心底的名字 (Your Name Engraved Herein) - 電影<刻在你心底的名字>主題曲',
                  url: 'https://open.spotify.com/track/3OC84eKMxRJ4x0Hcwl9i4i',
                },
                {
                  artist: 'Eason Chan',
                  position: '7',
                  streams: '110354',
                  trackId: '4IkQXb1IdIziAJmO3FODo7',
                  trackName: '是但求其愛',
                  url: 'https://open.spotify.com/track/4IkQXb1IdIziAJmO3FODo7',
                },
                {
                  artist: 'Dear Jane',
                  position: '8',
                  streams: '100095',
                  trackId: '0pupuSkMBGpzsqG3fWcyPe',
                  trackName: '銀河修理員',
                  url: 'https://open.spotify.com/track/0pupuSkMBGpzsqG3fWcyPe',
                },
                {
                  artist: 'Hins Cheung',
                  position: '9',
                  streams: '93556',
                  trackId: '4ckh5VN2HYQ8TzS51Nh7ol',
                  trackName: '俏郎君',
                  url: 'https://open.spotify.com/track/4ckh5VN2HYQ8TzS51Nh7ol',
                },
                {
                  artist: 'Dear Jane',
                  position: '10',
                  streams: '82566',
                  trackId: '3pciLZ7pj3WiwP8AmKdze8',
                  trackName: '未開始已經結束',
                  url: 'https://open.spotify.com/track/3pciLZ7pj3WiwP8AmKdze8',
                },
                {
                  artist: 'Joey Yung',
                  position: '11',
                  streams: '76465',
                  trackId: '1qc9E4zCJ5utXDQVIAZlkm',
                  trackName: '東京人壽',
                  url: 'https://open.spotify.com/track/1qc9E4zCJ5utXDQVIAZlkm',
                },
                {
                  artist: 'Terence Lam',
                  position: '12',
                  streams: '74215',
                  trackId: '24tzRRz8r26gOmQB8PEZwv',
                  trackName: '拼命無恙 in Bb major',
                  url: 'https://open.spotify.com/track/24tzRRz8r26gOmQB8PEZwv',
                },
                {
                  artist: 'BTS',
                  position: '13',
                  streams: '72317',
                  trackId: '4saklk6nie3yiGePpBwUoc',
                  trackName: 'Dynamite',
                  url: 'https://open.spotify.com/track/4saklk6nie3yiGePpBwUoc',
                },
                {
                  artist: 'Karen Mok',
                  position: '14',
                  streams: '71757',
                  trackId: '4t53NE3uBLkTwW9rUgiHC8',
                  trackName: '呼吸有害',
                  url: 'https://open.spotify.com/track/4t53NE3uBLkTwW9rUgiHC8',
                },
                {
                  artist: 'Jace Chan',
                  position: '15',
                  streams: '71688',
                  trackId: '7egdaSVtPnuW7YG821w7jz',
                  trackName: '隔離',
                  url: 'https://open.spotify.com/track/7egdaSVtPnuW7YG821w7jz',
                },
                {
                  artist: 'Justin Bieber',
                  position: '16',
                  streams: '68106',
                  trackId: '31qCy5ZaophVA81wtlwLc4',
                  trackName: 'Anyone',
                  url: 'https://open.spotify.com/track/31qCy5ZaophVA81wtlwLc4',
                },
                {
                  artist: '陳卓賢 Ian',
                  position: '17',
                  streams: '67482',
                  trackId: '1jVw3apCOogFU1mOquNIhC',
                  trackName: '正式開始',
                  url: 'https://open.spotify.com/track/1jVw3apCOogFU1mOquNIhC',
                },
                {
                  artist: 'Ariana Grande',
                  position: '18',
                  streams: '66534',
                  trackId: '35mvY5S1H3J2QZyna3TFe0',
                  trackName: 'positions',
                  url: 'https://open.spotify.com/track/35mvY5S1H3J2QZyna3TFe0',
                },
                {
                  artist: 'LiSA',
                  position: '19',
                  streams: '65742',
                  trackId: '0cSkn2l67csUljEy0EEBPn',
                  trackName: '炎',
                  url: 'https://open.spotify.com/track/0cSkn2l67csUljEy0EEBPn',
                },
                {
                  artist: 'Dear Jane',
                  position: '20',
                  streams: '63961',
                  trackId: '2mh20y35EhzqMy6su3sJJA',
                  trackName: '哀的美敦書',
                  url: 'https://open.spotify.com/track/2mh20y35EhzqMy6su3sJJA',
                },
                {
                  artist: '831',
                  position: '21',
                  streams: '63322',
                  trackId: '69zgyr5HVKdInjeKpq1qHa',
                  trackName: '想見你想見你想見你(電視劇"想見你"片尾曲)',
                  url: 'https://open.spotify.com/track/69zgyr5HVKdInjeKpq1qHa',
                },
                {
                  artist: 'Ed Sheeran',
                  position: '22',
                  streams: '63225',
                  trackId: '0E4Y1XIbs8GrAT1YqVy6dq',
                  trackName: 'Afterglow',
                  url: 'https://open.spotify.com/track/0E4Y1XIbs8GrAT1YqVy6dq',
                },
                {
                  artist: 'Ren Ran',
                  position: '23',
                  streams: '60951',
                  trackId: '3IveWAHTMxZA4KYBPnylq5',
                  trackName: '飞鸟和蝉',
                  url: 'https://open.spotify.com/track/3IveWAHTMxZA4KYBPnylq5',
                },
                {
                  artist: 'BLACKPINK',
                  position: '24',
                  streams: '60651',
                  trackId: '4SFknyjLcyTLJFPKD2m96o',
                  trackName: 'How You Like That',
                  url: 'https://open.spotify.com/track/4SFknyjLcyTLJFPKD2m96o',
                },
                {
                  artist: 'BLACKPINK',
                  position: '25',
                  streams: '57611',
                  trackId: '4Ws314Ylb27BVsvlZOy30C',
                  trackName: 'Lovesick Girls',
                  url: 'https://open.spotify.com/track/4Ws314Ylb27BVsvlZOy30C',
                },
                {
                  artist: 'The Weeknd',
                  position: '26',
                  streams: '56002',
                  trackId: '5QO79kh1waicV47BqGRL3g',
                  trackName: 'Save Your Tears',
                  url: 'https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g',
                },
                {
                  artist: 'YOASOBI',
                  position: '27',
                  streams: '55540',
                  trackId: '6MCjmGYlw6mQVWRFVgBRvB',
                  trackName: '夜に駆ける',
                  url: 'https://open.spotify.com/track/6MCjmGYlw6mQVWRFVgBRvB',
                },
                {
                  artist: 'Dua Lipa',
                  position: '28',
                  streams: '55522',
                  trackId: '5nujrmhLynf4yMoMtj8AQF',
                  trackName: 'Levitating (feat. DaBaby)',
                  url: 'https://open.spotify.com/track/5nujrmhLynf4yMoMtj8AQF',
                },
                {
                  artist: '姜濤',
                  position: '29',
                  streams: '55382',
                  trackId: '2w9A7fvq6ka5CB9l7wDZXG',
                  trackName: '蒙著嘴說愛你',
                  url: 'https://open.spotify.com/track/2w9A7fvq6ka5CB9l7wDZXG',
                },
                {
                  artist: 'Taylor Swift',
                  position: '30',
                  streams: '55136',
                  trackId: '3Uo7WG0vmLQ07WB4BDwy7D',
                  trackName: 'willow',
                  url: 'https://open.spotify.com/track/3Uo7WG0vmLQ07WB4BDwy7D',
                },
                {
                  artist: 'Charmaine Fong',
                  position: '31',
                  streams: '55122',
                  trackId: '53HxUdYRCRMdzYPG0qhGUP',
                  trackName: '假使世界原來不像你預期',
                  url: 'https://open.spotify.com/track/53HxUdYRCRMdzYPG0qhGUP',
                },
                {
                  artist: 'Lewis Capaldi',
                  position: '32',
                  streams: '55006',
                  trackId: '7qEHsqek33rTcFNT9PFqLf',
                  trackName: 'Someone You Loved',
                  url: 'https://open.spotify.com/track/7qEHsqek33rTcFNT9PFqLf',
                },
                {
                  artist: 'Ariana Grande',
                  position: '33',
                  streams: '54931',
                  trackId: '6Im9k8u9iIzKMrmV7BWtlF',
                  trackName: '34+35',
                  url: 'https://open.spotify.com/track/6Im9k8u9iIzKMrmV7BWtlF',
                },
                {
                  artist: 'Serrini',
                  position: '34',
                  streams: '54832',
                  trackId: '5x9Clj56YLmklm3Zikx2iF',
                  trackName: '我在流浮山滴眼水.jpg',
                  url: 'https://open.spotify.com/track/5x9Clj56YLmklm3Zikx2iF',
                },
                {
                  artist: 'Hins Cheung',
                  position: '35',
                  streams: '54159',
                  trackId: '2WVbMoHdWCspdiEa7OnG1D',
                  trackName: '春秋',
                  url: 'https://open.spotify.com/track/2WVbMoHdWCspdiEa7OnG1D',
                },
                {
                  artist: 'Terence Lam',
                  position: '36',
                  streams: '53870',
                  trackId: '3PeCYcmMwmxshV64hPSHGS',
                  trackName: '特倫斯夢遊仙境',
                  url: 'https://open.spotify.com/track/3PeCYcmMwmxshV64hPSHGS',
                },
                {
                  artist: 'SZA',
                  position: '37',
                  streams: '53577',
                  trackId: '3YJJjQPAbDT7mGpX3WtQ9A',
                  trackName: 'Good Days',
                  url: 'https://open.spotify.com/track/3YJJjQPAbDT7mGpX3WtQ9A',
                },
                {
                  artist: 'Shawn Mendes',
                  position: '38',
                  streams: '53478',
                  trackId: '1HbA4N1MiOsPthALesGFR1',
                  trackName: 'Monster (Shawn Mendes & Justin Bieber)',
                  url: 'https://open.spotify.com/track/1HbA4N1MiOsPthALesGFR1',
                },
                {
                  artist: 'Billie Eilish',
                  position: '39',
                  streams: '52169',
                  trackId: '54bFM56PmE4YLRnqpW6Tha',
                  trackName: 'Therefore I Am',
                  url: 'https://open.spotify.com/track/54bFM56PmE4YLRnqpW6Tha',
                },
                {
                  artist: 'Dear Jane',
                  position: '40',
                  streams: '52025',
                  trackId: '6pJT4f6S8GPQ7hWCDvygrN',
                  trackName: '2084',
                  url: 'https://open.spotify.com/track/6pJT4f6S8GPQ7hWCDvygrN',
                },
                {
                  artist: 'Jason Chan',
                  position: '41',
                  streams: '50384',
                  trackId: '1eId3TVzGrwv73YAWAVQMX',
                  trackName: '你瞞我瞞',
                  url: 'https://open.spotify.com/track/1eId3TVzGrwv73YAWAVQMX',
                },
                {
                  artist: 'JC 陳詠桐',
                  position: '42',
                  streams: '49946',
                  trackId: '1ldMLpWMFcD28gbd9TICkv',
                  trackName: '我該放手',
                  url: 'https://open.spotify.com/track/1ldMLpWMFcD28gbd9TICkv',
                },
                {
                  artist: 'Maroon 5',
                  position: '43',
                  streams: '49546',
                  trackId: '2b8fOow8UzyDFAE27YhOZM',
                  trackName: 'Memories',
                  url: 'https://open.spotify.com/track/2b8fOow8UzyDFAE27YhOZM',
                },
                {
                  artist: 'Shawn Mendes',
                  position: '44',
                  streams: '49146',
                  trackId: '6v3KW9xbzN5yKLt9YKDYA2',
                  trackName: 'Señorita',
                  url: 'https://open.spotify.com/track/6v3KW9xbzN5yKLt9YKDYA2',
                },
                {
                  artist: 'Jay Chou',
                  position: '45',
                  streams: '48305',
                  trackId: '56wVfJKtnwlSZtC4NVgIrf',
                  trackName: '說好不哭',
                  url: 'https://open.spotify.com/track/56wVfJKtnwlSZtC4NVgIrf',
                },
                {
                  artist: 'Kay Tse',
                  position: '46',
                  streams: '48186',
                  trackId: '3hU9nGBhYJQwvF8BJ4PUcE',
                  trackName: '囍帖街',
                  url: 'https://open.spotify.com/track/3hU9nGBhYJQwvF8BJ4PUcE',
                },
                {
                  artist: 'BTS',
                  position: '47',
                  streams: '47001',
                  trackId: '249gnXrbfmV8NG6jTEMSwD',
                  trackName: 'Life Goes On',
                  url: 'https://open.spotify.com/track/249gnXrbfmV8NG6jTEMSwD',
                },
                {
                  artist: 'RubberBand',
                  position: '48',
                  streams: '46862',
                  trackId: '5OPqZ5dEqrdPGatJgnZ8xG',
                  trackName: '未來見',
                  url: 'https://open.spotify.com/track/5OPqZ5dEqrdPGatJgnZ8xG',
                },
                {
                  artist: 'Jer 柳應廷',
                  position: '49',
                  streams: '46271',
                  trackId: '33c5MYdr80WqXws9pj06b4',
                  trackName: '水刑物語',
                  url: 'https://open.spotify.com/track/33c5MYdr80WqXws9pj06b4',
                },
                {
                  artist: 'Billie Eilish',
                  position: '50',
                  streams: '43448',
                  trackId: '0psS4i5YooJrXfDnGvWRLi',
                  trackName: 'Lo Vas A Olvidar (with ROSALÍA)',
                  url: 'https://open.spotify.com/track/0psS4i5YooJrXfDnGvWRLi',
                },
                {
                  artist: 'Justin Bieber',
                  position: '51',
                  streams: '42163',
                  trackId: '4y4spB9m0Q6026KfkAvy9Q',
                  trackName: 'Lonely (with benny blanco)',
                  url: 'https://open.spotify.com/track/4y4spB9m0Q6026KfkAvy9Q',
                },
              ],
            },
          });
        });
    });
    const { result, waitFor } = renderHook(() => useTopStreamingAlbum(), {
      wrapper: ({ children }) => <TestApp>{children}</TestApp>,
    });
    await waitFor(() => expect(result.current?.data).toBeDefined());
    expect(result.current?.data).toHaveProperty('albums');
    expect(result.current?.data.albums.length).toBeGreaterThan(0);
    expect(result.current?.data.albums.length).toBeLessThanOrEqual(50);
  });
});
