name: Test systems/http-api

on:
  push:
    branches:
      - development
      - master
    paths:
      - 'systems/http-api/**'
  pull_request:
    paths:
      - 'systems/http-api/**'
env:
  CI: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::set-output name=PYTHON_VERSION::$(cat ./systems/http-api/.python-version)
        id: python-version
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ steps.python-version.outputs.PYTHON_VERSION }}'
      - run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: bash ./scripts/setup.sh
      - run: lerna exec --stream --concurrency 1 --scope=@music-player/http-api -- bash scripts/ci/setup.sh
      - run: lerna exec --stream --concurrency 1 --scope=@music-player/http-api -- bash scripts/ci/test.sh